edit_uri: edit/main/docs
extra:
  homepage: /overview
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.highlight:
      use_pygments: true
      pygments_lang_class: true
      line_spans: __span
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 
nav:
  - Overview: overview/index.md
  - Introduction:
      - 'What is Kubernetes?': introduction/what-is-kubernetes.md
      - 'Kubernetes Architecture': introduction/architecture.md
  - Setup:
      - 'Installation': setup/installation.md
      - 'Cluster Creation': setup/cluster-creation.md
  - 'Workloads on Kubernetes':
      - workloads/index.md
      - 'Pods': workloads/pods.md
      - 'Deployments': workloads/deployments.md
      - 'DaemonSets': workloads/daemonsets.md
plugins:
  - git-revision-date-localized:  
      enable_creation_date: true
  - glightbox
  
repo_url: https://github.com/mocdaniel/k8s-primer
site_name: Kubernetes Primer
theme:
  favicon: assets/images/favicon.png
  features:
    - content.action.edit
    - content.action.view
    - content.code.copy
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.path
    - toc.follow
  icon:
    annotation: material/help-circle
    logo: simple/kubernetes
  name: material
  palette:
    primary: deep orange
    accent: amber
