copyright: Copyright &copy; 2023 Daniel Bodky
extra:
  homepage: /overview
  social:
    - icon: material/github
      link: https://github.com/mocdaniel
      name: mocdaniel on GitHub
    - icon: material/twitter
      link: https://twitter.com/d_bodky
      name: mocdaniel on Twitter
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.highlight:
      use_pygments: true
      pygments_lang_class: true
      line_spans: __span
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 
nav:
  - Overview: overview/index.md
  - Introduction:
      - 'What is Kubernetes?': introduction/what-is-kubernetes.md
      - 'Kubernetes Architecture': introduction/architecture.md
  - Setup:
      - 'Installation': setup/installation.md
      - 'Cluster Creation': setup/cluster-creation.md
  - 'Workloads on Kubernetes':
      - workloads/index.md
      - 'Pods': workloads/pods.md
      - 'Deployments':
          - workloads/deployments/index.md
          - 'Creating Deployments': workloads/deployments/create.md
          - 'Scaling Deployments': workloads/deployments/scale.md
          - 'Updating and Restoring Deployments': workloads/deployments/update.md
      - 'DaemonSets': workloads/daemonsets.md
  - 'Networking on Kubernetes':
      - network/index.md
      - 'Pod Networking': network/pod-networking.md
      - 'Services': 
          - network/services/index.md
      - 'Ingress': network/ingress.md
plugins:
  - git-revision-date-localized:
      enable_creation_date: true
  - glightbox
repo_name: mocdaniel/k8s-primer
repo_url: https://github.com/mocdaniel/k8s-primer
site_name: Kubernetes Primer
theme:
  favicon: assets/images/favicon.png
  features:
    - content.code.copy
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.path
    - toc.follow
  icon:
    annotation: material/help-circle
    logo: simple/kubernetes
    repo: fontawesome/brands/github
  name: material
  palette:
    primary: deep orange
    accent: amber
